### ISSUE TITLE
add attr nomenclature-citation-list-type

### ISSUE THREAD

**Issue by tcatapano** [plazi/TaxPub#10]

**Comment by tcatapano** [comment]
@myrmoteras : what would be some values of this type attribute? "synonymy"... anything else? Might be best to create a taxoomy-specific attribute rather than a generic type. Perhaps a "synonomy=yes|no"? How many different "types" of nomenclature-citation-lists (i.e., treatment citation groups) do we care about?

**Comment by myrmoteras** [comment]
not sure what you mean. @gsautter might be better to help. One type is the creation of a new synonymy. the other is to cite a synonymy in a previous work, ie confirming a previous new synonymy.

See also https://github.com/plazi/Plazi-Communications/issues/830 for the labels for new synonymies etc.

**Comment by gsautter** [comment]
The two types @myrmoteras listed are definitely the ones we need when new synonymies are created. A third type might be simply listing previous original and re-descriptions of a taxon. Oh, and a fourth type would be citation(s) of the basionym in a new combination.

**Comment by tcatapano** [comment]
added content-type attribute as it is sufficient for specifying semantics which is the purpose here. Leaving out any values...
