### ISSUE TITLE
expansion of abbreviated genus names

### ISSUE THREAD

**Issue by tcatapano** [plazi/TaxPub#17]
from @pdatascience

> ... we know that P. damicornis =
Pocillopora damicornis in this context but there is no way to express
it in TaxPub (at least we don’t know how). In the XML we have

```
<tp:taxon-name>

<tp:taxon-name-part taxon-name-part-type="genus">P.</tp:taxon-name-part>

<tp:taxon-name-part
taxon-name-part-type="species">damicornis</tp:taxon-name-part>

</tp:taxon-name>
```

where to put the full/expanded genus name "Pocillopora"

**Comment by tcatapano** [comment]
@pdatascience

the `@reg` "regularized name" attribute of the `tp:taxon-name-part` can be used to store the full genus name is its regularized form:

```
<tp:taxon-name>
<tp:taxon-name-part taxon-name-part-type="genus" reg="Pocillopora">P.</tp:taxon-name-part>
<tp:taxon-name-part taxon-name-part-type="species">damicornis</tp:taxon-name-part>
</tp:taxon-name>
```

**Comment by pdatascience** [comment]
This is actually extremely helpful now! I need to discuss this with Teodor? Could you, please add him to the thread?

**Comment by pdatascience** [comment]
For now, I will send him a mail with this.

**Comment by tcatapano** [comment]
as per @pdatascience adding @teodorgeorgiev to thread

**Comment by tcatapano** [comment]
Closing.
