### ISSUE TITLE
encoding of proper taxon concept label

### ISSUE THREAD

**Issue by tcatapano** [plazi/TaxPub#18]
from @pdatascience

> How would I encode a proper
taxon concept label such as Pocillopora damicornis sec. Poquita-Du et.
Al (2017)?

e.g., 

```
<tp:taxon-name>

<tp:taxon-name-part
taxon-name-part-type="genus">Pocillopora</tp:taxon-name-part>

<tp:taxon-name-part
taxon-name-part-type="species">damicornis</tp:taxon-name-part>

<to:taxon-name-part taxon-name-part-type=”sec”>sec. Poquita-Du et. Al
(2017)? </tp:taxon-name-part>

</tp:taxon-name>

```

**Comment by tcatapano** [comment]
@patascience:

This encoding is fine, although I'd suggest using something more standard than "sec" as the value of @taxon-name-part-type. @myrmoteras might suggest a term.

**Comment by pdatascience** [comment]
Sec. is the de-facto standard suggested by Nico Franz for encoding the reference part of a taxon concept label. He specifically avoids the usage of sensu as it can be confused with things like "sensu lato" and "sensu stricto".

**Comment by tcatapano** [comment]
@pdatascience: understood. The value of the `reg` attribute is not controlled so this would work. I was just unfamiliar with 'sec'.
