### ISSUE TITLE
define section types (subSubSection types in GG)

### ISSUE THREAD

**Issue by myrmoteras** [plazi/TaxPub#23]
@gsautter @tcatapano   Following is a list of section types to be included in taxpub, especially for EJT and then implmented in GoldenGateImagine

![image](https://user-images.githubusercontent.com/4609956/34324602-3064d4f0-e879-11e7-8b9b-3b8a63ccea91.png)

`keywords` to include all the keywords listed in this section. Ideally they are parsed out and also submitted to BLR

`materials_methods` Materials and methods is a standard section in scientific papers describing the methods, standards, abbreviations, materials used in the article. This is already introduced, but hardly ever used (at least by me)

`results` this section describes the results obtained in the study. In taxonomic studies it also includes the treatments.

`discussion` This section explains the results, puts them in context and draws conclusion (sometimes its own subSubSection. In EJT it has subSubSubSections which are not generic put specific to the article

`conservation` This section discusses the conservation status of the respective taxon, including often references to RedLists and management plans.

**Sections specific to EJT**

`backmatter` includes all the description of the history of the manuscript, distribution of the article

`document-head` includes all the headers, title, authors, affiliations of the authors, emails, Zoobank numbers. this seems to be the same as `frontatter`

`citation` includes the suggested way to cite the article

**Comment by myrmoteras** [comment]
subSubsection type =materials_methods

this section often has subSubSubsections. I don't know what to do with it?
![image](https://user-images.githubusercontent.com/4609956/34324622-ca5b5552-e879-11e7-92a6-16278daff065.png)

**Comment by myrmoteras** [comment]
subSubSection type = results

![image](https://user-images.githubusercontent.com/4609956/34324630-2f723eec-e87a-11e7-8b3b-c79835878a93.png)

**Comment by myrmoteras** [comment]
subSubSection type = discussion

![image](https://user-images.githubusercontent.com/4609956/34324642-8de5f932-e87a-11e7-84b0-9afe6636e117.png)

**Comment by myrmoteras** [comment]
subSubSection type = backmatter

![image](https://user-images.githubusercontent.com/4609956/34324701-11b1d0d2-e87c-11e7-90bc-edffebc08b8c.png)

**Comment by myrmoteras** [comment]
subSubSection type = frontmatter, citation

![image](https://user-images.githubusercontent.com/4609956/34324710-b8cdd384-e87c-11e7-9c32-bb7ccdecb682.png)

**Comment by tcatapano** [comment]
To be consistent with the JATS model, we should consider Abstract, Keywords, and Citation as components of Front Matter.

**Comment by myrmoteras** [comment]
but are those named parts in the Front Matter, thus subSubSecton of subsection type=frontMatter? Or how do we have to mark up this section?
Can you let @gsautter know?

**Comment by gsautter** [comment]
@tcatapano no need to ... following anyway.

**Comment by gsautter** [comment]
Just need some idea about how to identify these individual types ...
- "Abstract" and "Keywords" should be straightforward (I tend to think we already have "abstract" anyway, so only the keywords to add)
- "Citation" might be a bit more of a challenge
- "FrontMatter" appears to be pretty much equivalent to what is now "document_head"

**Comment by tcatapano** [comment]
This is a little vague to me. Not sure what to check on. I'll deal with it
when I get samples with the new sec-types.

**Comment by myrmoteras** [comment]
@tcatapano 
You can use all the EJT- > EJT-380, where I started to add the section types mentioned above.

Citation (see image at the top of this issue) is essentially a bibRef in the front matter. When you do the mark up of the bibRef in EJT, this is always the first bibRef that is discovered by the tagger and neeed then be removed.

**Comment by gsautter** [comment]
Add "phylogeny" (see https://github.com/plazi/Plazi-Communications/issues/750 for example).

**Comment by tcatapano** [comment]
I think should be recommended values, which can be enforced via schematron.

**Comment by tcatapano** [comment]
Removing from 1.0 milestone

**Comment by tcatapano** [comment]
See #73 . Closing
