### ISSUE TITLE
download and ship taxpub files

### ISSUE THREAD

**Issue by myrmoteras** [plazi/TaxPub#24]
@tcatapano I want to look at the valid XML files and add them to the dropbox.
1. I can't find the file, but on github https://github.com/plazi/EJT-testbed/blob/master/test_output/ejt-408_dautova_xml_id_tp.xml
2. When I copy and past the file into oxygen, and validate, the dtd is missing. Where is it? `file:/Users/terry/Github/TaxPub/tax-treatment-NS0-v1.dtd`

**Comment by tcatapano** [comment]
This is actually an issue for EJT-testbed. At any rate, I'll address the issue in a few hours. I have to go to work now.

**Comment by tcatapano** [comment]
Closing
