### ISSUE TITLE
UUIDs in JATS/TaxPub id attributes

### ISSUE THREAD

**Issue by teodorgeorgiev** [plazi/TaxPub#31]
https://github.com/pensoft/PJS/issues/896#issue-291624833

**Comment by teodorgeorgiev** [comment]
OpenBiodiv generates UUID's to various elements in the XML. The list is still growing but at the moment it encompasses the following XML elements:
```
title: /article/front/article-meta/title-group/article-title
abstract: /article/front/article-meta/abstract
front_matter: /article/front
figures: /article/floats-group//fig
plates: /article/floats-group/fig-group
tables: /article/floats-group/table-wrap
reference_list: /article/back/ref-list
reference: /article/back/ref-list/ref
back_matter: /article/back
acknowledgement: /article/back/ack
body: /article/body
treatment: /article/body/sec/tp:taxon-treatment
nomenclature_heading: /article/body//tp:taxon-treatment/tp:nomenclature
nomenclature_citation_list: /article/body//tp:taxon-treatment/tp:nomenclature/tp:nomenclature-citation-list
treatment_section: /article/body/tp:taxon-treatment/tp:treatment-sec
sec: .//sec
captions: .//caption
authors: /article/front/article-meta/contrib-group/contrib
paper_type: /article/front/article-meta/article-categories/subj-group[@subj-group-type='heading']
taxon_classification: /article/front/article-meta/article-categories/subj-group[@subj-group-type='Taxon classification']
subject_classification: /article/front/article-meta/article-categories/subj-group[@subj-group-type='Subject classification']
geographic_classification: /article/front/article-meta/article-categories/subj-group[@subj-group-type='Geographical classification']
zookeys_keywords: /article/front/article-meta/kwd-group
taxonomic_name_usage: .//tp:taxon-name
named-content[@content-type='dwc:institutional_code']
```

To avoid data duplication if the XML is to be regenerated, the PWT process needs to generate these IDs.
We need to have a connection between Instance ID and UUID. They must appear in PREVIEW and a "modified" NLM must be available where the ID's have the attribute "obkms_id". However, they need to be hidden before submission to NLM.

File-Based process: upon generation of the preview, check the elements (whether they have ID) and then generate ID.

**Comment by tcatapano** [comment]
possible solution: append UUID to existing id value, with or without a delimiter (e.g., underscore). This will insure uniqueness of the id, is opaque and innocuous to outside users, but enables local semantics

**Comment by tcatapano** [comment]
Another, perhaps better, solution is to put the treatment UUID in a treatment-meta section.

**Comment by teodorgeorgiev** [comment]
or probably can use <taxon-identifier></taxon-identifier>

**Comment by tcatapano** [comment]
See also `<object-id>` https://jats.nlm.nih.gov/publishing/tag-library/1.3/element/object-id.html when permitted
