### ISSUE TITLE
Elements without id attributes

### ISSUE THREAD

**Issue by tcatapano** [plazi/TaxPub#32]

**Comment by vsenderov** [comment]
List of elements that have OBKMS_ID's can be compiled from

```
https://github.com/pensoft/ropenbio/blob/redesign/R/taxpub.R
```
Look at the `xpath` fields in the objects. E.g.

```
xpath = "/article/front/article-meta/kwd-group"
```

**Comment by tcatapano** [comment]
will add %jats-common-atts to all elements

**Comment by tcatapano** [comment]
`@id` is included in all elements in commit https://github.com/plazi/TaxPub/commit/cc600a0880355d1d5c0453fa2e332d7094335b47

But note important distinction between `<@id>` and `<object-id>` as discussed in the JATS Tag Library:

- [`@id`](https://jats.nlm.nih.gov/publishing/tag-library/1.3/attribute/id.html)
> Unique internal identifier of an element; allows element to be cross-referenced (made into a link). Value must be unique across a document, not just for an element type. 
- [ `<object-id>``](https://jats.nlm.nih.gov/publishing/tag-library/1.3/element/object-id.html)
> The [`<object-id>`](https://jats.nlm.nih.gov/publishing/tag-library/1.3/element/object-id.html) element holds an external identifier, typically assigned to an object such as a table by a publisher. The contents of this element should not be confused with the [`@id`](https://jats.nlm.nih.gov/publishing/tag-library/1.3/attribute/id.html) attribute, which holds an internal document identifier that can be used by software to perform a simple link inside the document.

**Comment by tcatapano** [comment]
Closing
