### ISSUE TITLE
genus type species: in what element does it belong

### ISSUE THREAD

**Issue by myrmoteras** [plazi/TaxPub#37]
in which subSubSection type belong the Type species?
![image](https://user-images.githubusercontent.com/4609956/49987058-51e33700-ff72-11e8-8a32-4ed9d4ec7d30.png)

type=nomenclature or type=materials_citation?

I use type=nomenclature

ejt-486_constant

**Comment by tcatapano** [comment]
`<tp:type-genus>` is intended as a nomenclature element and is permitted as a child only in those elements

see: http://taxpub.org/v1-0/taglibrary/index.html#p=elem-tp-type-genus

Closing
