### ISSUE TITLE
allow nomenclature-citation-list and nomenclature-citation elsewhere in taxon-treatment

### ISSUE THREAD

**Issue by tcatapano** [plazi/TaxPub#39]
see also #33, #10, #34

**Comment by tcatapano** [comment]
@myrmoteras could you provide some examples of treatments with treatment citations outside the nomenclature section? That would be very helpful.

**Comment by myrmoteras** [comment]
allmost all treatment citations are in type=reference_group. Hardly ever in nomenclature

**Comment by tcatapano** [comment]
nomenclature-citation-group now allowed as child of treatment-sec. Will investigate need for nomenclature-citation-list, nomenclature-citation. Examples needed

**Comment by myrmoteras** [comment]
zootaxa.4668.1.1 treatmentCitation in treatmentCitationGroup

![image](https://user-images.githubusercontent.com/4609956/64949562-bfaded80-d879-11e9-9c8d-9dca716073f6.png)

![image](https://user-images.githubusercontent.com/4609956/64949622-dd7b5280-d879-11e9-9049-985a17a2a190.png)

**Comment by myrmoteras** [comment]
same article, only one treatmentCitation

![image](https://user-images.githubusercontent.com/4609956/64949819-55497d00-d87a-11e9-8d3d-ed7d23c69f30.png)


![image](https://user-images.githubusercontent.com/4609956/64949790-44007080-d87a-11e9-9d23-2a81b1133a30.png)

**Comment by myrmoteras** [comment]
zootaxa.4668.1.2

![image](https://user-images.githubusercontent.com/4609956/64950526-dd7c5200-d87b-11e9-8956-70854957da3f.png)

**Comment by tcatapano** [comment]
Allowed as child of any `<treatment-sec>` in commit https://github.com/plazi/TaxPub/commit/b5cecc68a0c509d5588e19617e4d6cf97aea7e82
Closing
