### ISSUE TITLE
validation issue: one sec in a treatment enough?

### ISSUE THREAD

**Issue by myrmoteras** [plazi/TaxPub#48]
@tcatapano in thsi BDJ, there are treatments that have only one sec in a treatment. https://bdj.pensoft.net/article/6313/element/7/0/viburnum%20lantana/
it seems that this validates, although I thought that the definition of a treatments requires at least two sec?

https://bdj.pensoft.net/article/6313/element/7/0/viburnum%20lantana/

https://bdj.pensoft.net/article/6313/download/xml/

![image](https://user-images.githubusercontent.com/4609956/116895563-a070f900-ac33-11eb-88fb-ec907df53f9d.png)

and here the one sec treatment in Plazi TB 
http://tb.plazi.org/GgServer/html/FEA877B9AE9D425E243213D965AE88D2

**Comment by tcatapano** [comment]
this is fine. See the content model of `<tp:taxon-treatment>`: http://taxpub.catapanoth.com/v1-pre/documentation/#p=elem-tp-taxon-treatment

```
( tp:treatment-meta?, tp:nomenclature, ( tp:treatment-sec | tp:taxon-treatment )*, ref-list? )

```

an optional `tp:treatment-meta`, followed by a required `tp:nomenclature`, followed by zero or more `tp:treatment-sec`s or `tp:taxon-treatment`s, followed by an optional `ref-list`
