### ISSUE TITLE
how to annotate species: new taxa registration

### ISSUE THREAD

**Issue by myrmoteras** [plazi/TaxPub#55]
@tcatapano 

what is correct to add a persistent http uri? When to use what? 

`<named-content content-type="phycobank" xlink:href="http://phycobank.org/103328">Phycobank 103328</named-content>`

or

`<object-id content-type="zoobank" xlink:type="simple">https://zoobank.org/63BC2367-9654-45DA-8021-FD17584DFFDC</object-id> ` 

This is also how it is used in ZooKeys  https://zookeys.pensoft.net/article/86448/download/xml/

see https://docs.google.com/document/d/119Q23aispfZgOZpfpCh0V6Z0S8sClJz-/edit# 

or

`<mixed-citation><object-id content-type="taxonomic_treatment" object-id-type="doi">[DOI]</object-id></mixed-citation>`

**Comment by tcatapano** [comment]
These are all JATS usage issues, not TaxPub issues *per se*.  See the discussions and definitions of these elements in the JATS Tag Library

- `<named-content>`: https://jats.nlm.nih.gov/publishing/tag-library/1.3/element/named-content.html
  - see [`@vocab-term`](https://jats.nlm.nih.gov/publishing/tag-library/1.3/attribute/vocab-term.html) and [`xlink:href`](https://jats.nlm.nih.gov/publishing/tag-library/1.3/attribute/xmlns-xlink.html) attributes

- `<object-id>`: https://jats.nlm.nih.gov/publishing/tag-library/1.3/element/object-id.html

> The [`<object-id>`](https://jats.nlm.nih.gov/publishing/tag-library/1.3/element/object-id.html) element holds an external identifier, typically assigned to an object such as a table by a publisher. The contents of this element should not be confused with the [`@id`](https://jats.nlm.nih.gov/publishing/tag-library/1.3/attribute/id.html) attribute, which holds an internal document identifier that can be used by software to perform a simple link inside the document.

- `<mixed-citation>`: https://jats.nlm.nih.gov/publishing/tag-library/1.3/element/mixed-citation.html

also see:

- `<uri>` which may be contained in `<named-content>` and `<mixed-citation>`, in cases in which the identifier is a URI
> Identifies a Uniform Resource Identifier (such as a URL) that may be used as a live link, typically naming a website... While the <uri> element has the form of a URI such as a URL, it is not automatically a link, nor even expected to be a live link. To make this element into a live link, add the XLink [@xlink:href](https://jats.nlm.nih.gov/publishing/tag-library/1.3/attribute/xlink-href.html) attribute.

Closing.
