### ISSUE TITLE
uuid vs httpUrl; PID vs httpPID

### ISSUE THREAD

**Issue by myrmoteras** [plazi/TaxPub#58]
What is the recommended startegy in cases where a PID is given (for example as accession number) but not with a URL, but the URL can be built with a known prefix+accession number.

eg `AM932788`

`<named-content content-type="NCBI" xlink:href="https://www.ncbi.nlm.nih.gov/nuccore/AM932788">AM932788</named-content>`

**Comment by tcatapano** [comment]
The example provided makes sense. Verbatim UUID as the text of `<named-content>` and HTTP URI form in  the `xlink:href` element.

**Comment by tcatapano** [comment]
closing
