### ISSUE TITLE
how to annotate persons

### ISSUE THREAD

**Issue by myrmoteras** [plazi/TaxPub#59]
@tcatapano here is the annoation of a person aka contributor  in https://zookeys.pensoft.net/article/81125/download/xml/

Can you pleas check the use of ORCID. This seems to be yet another way to annotate a persistent identifier (see other cases in https://github.com/plazi/TaxPub/issues/56

`<contrib contrib-type="author" corresp="no">
<name name-style="western">
<surname>Liu</surname>
<given-names>Yuxin</given-names>
</name>
<uri content-type="orcid">https://orcid.org/0000-0002-0241-1036</uri>
<xref ref-type="aff" rid="A1">1</xref>
</contrib>`

This seems to me not correct?!

**Comment by tcatapano** [comment]
`<contrib-id>` should be used. See https://jats.nlm.nih.gov/publishing/tag-library/1.3/element/contrib-id.html

> The [<contrib-id>](https://jats.nlm.nih.gov/publishing/tag-library/1.3/element/contrib-id.html) element holds an external identifier, typically assigned to a person by an agency such as the publisher, ORCID, or other personal identification authority. The contents of this element should not be confused with the [@id](https://jats.nlm.nih.gov/publishing/tag-library/1.3/attribute/id.html) attribute, which holds an internal document identifier that can be used by software to perform a simple link inside the XML document.
Type of Identifier Best Practice
Best Practice is to use the [@contrib-id-type](https://jats.nlm.nih.gov/publishing/tag-library/1.3/attribute/contrib-id-type.html) attribute to indicate the type of the external identifier, such as a publisher’s identifier, an ORCID, a SCOPUS identifier, or similar. (See [@contrib-id-type](https://jats.nlm.nih.gov/publishing/tag-library/1.3/attribute/contrib-id-type.html) for values.)

so

```
<contrib contrib-type="author" corresp="no"> <name name-style="western"> <surname>Liu</surname> <given-names>Yuxin</given-names> </name> <contrib-id content-id-type="orcid">https://orcid.org/0000-0002-0241-1036</uri> <xref ref-type="aff" rid="A1">1</xref> </contrib>
```

**Comment by teodorgeorgiev** [comment]
@myrmoteras @tcatapano 
Yes, this is because the provided example using jats 3.0 (which is used with the current release of taxpub), where the <contrib-id> element does not exist. In this case, as work around the orcid is included using <uri> element
Probably is good to decide what version of JATS and taxpub all examples should follow, and to state in the article that all recommendations/examples are based on JATS xx (released date), TaxPub yy (coming soon). What do you think?

**Comment by myrmoteras** [comment]
@teodorgeorgiev I think this is an important additional piece of the puzzle to add to the text. @tcatapano can please add it here and I then add it to the ms.

**Comment by myrmoteras** [comment]
@tcatapano 
is this also correct to annotate a collector in a material citation
(see [ID ms ](https://docs.google.com/document/d/119Q23aispfZgOZpfpCh0V6Z0S8sClJz-/edit#)page 31)
```
<contrib contrib-type="author">
<name name-style="western"> <surname>Sharaf</surname> <given-names>M. R.</given-names> </name>
<contrib-id contrib-id-type="orcid">https://orcid.org/0000-0001-8137-0705</contrib-id>
</contrib>
```

or should this be 

`<string-name>Sharaf, M.R.</string-name>`

**Comment by myrmoteras** [comment]
there is also the more general issue, how to annotate persons in the body of an article. row 35 in the [table](https://docs.google.com/spreadsheets/d/1n_-v8Ty9VO6Cg4mUL794K37I1QC0PJxs/edit?pli=1#gid=1287527644)

**Comment by myrmoteras** [comment]
this then is ok

`<named-content content-type="dwc:recordedBy">Liu Yu-Wei</named-content>`

[see](https://docs.google.com/document/d/119Q23aispfZgOZpfpCh0V6Z0S8sClJz-/edit) page 30

and row 35 in the [table](https://docs.google.com/spreadsheets/d/1n_-v8Ty9VO6Cg4mUL794K37I1QC0PJxs/edit#gid=1287527644)

**Comment by tcatapano** [comment]
Yes
