### ISSUE TITLE
JATS article title uuid

### ISSUE THREAD

**Issue by teodorgeorgiev** [plazi/TaxPub#65]
Hi @tcatapano the reason we would like to add an uuid also on the title element is consistency. To be able to express the following

article [UUID XXX] has
  title [UUID XX1]
  abstract [UUID XX2]
  keywords [UUID XX3]
  section [UUID XX4]
  etc.

Can we use something like that:
`<uri content-type="xyz-uuid">10700A07-3386-57EA-9C6B-121AB0998AA9</uri>`

**Comment by tcatapano** [comment]
@teodorgeorgiev I don't know enough about your use context, so am agnostic as to usage. That said, in JATS `<object-id>` is not available on `<title>` , that is the title the article, not in metadata, which would use the element `<article-title>`, which also does not allow `<object-id>`. You *could* use the `<uri>` element, but that usage should probably not be considered normative. My sense is that the `<uri>` element in `<title>` is intended to allow one to tag a uri which is part of a title, not to provide a identifier for the title. Up to you, though.

**Comment by teodorgeorgiev** [comment]
Thanks, @tcatapano. Of course, you are right ... am I just trying to find a workaround, but in all cases, we can skip that.
