### ISSUE TITLE
New TaxPub and JATS versions

### ISSUE THREAD

**Issue by teodorgeorgiev** [plazi/TaxPub#66]
Hi @tcatapano if I understand correctly the new TaxPub version will work with JATS 1.1. 
I am wondering, is there any particular reason for that? 
My point is that we need to put effort into rebuilding the entire XML document flow anyway, at least I'd like to do this based on the current latest versions.
Do you think this makes sense and is that realistic (in terms of time/effort) to align the new TaxPub to JATS 1.3?

**Comment by tcatapano** [comment]
The next version of TaxPub will be based on JATS 1.3. The *current* version of TaxPub is based on JATS 1.1

**Comment by tcatapano** [comment]
And to be clear. The next version will be based on JATS 1.3 *publishing*

**Comment by myrmoteras** [comment]
@tcatapano in the table and the article, should we reference 1.1 or 1.3? What do you recommend?

**Comment by teodorgeorgiev** [comment]
@tcatapano Thanks!

**Comment by tcatapano** [comment]
For generic and standalone JATS element, 1.3 (e.g., article metadata). For generic JATS elements used inside the taxonomy specific elements of TaxPub, 1.1 (e.g., anything at the treatment level or below).
