### ISSUE TITLE
taxpub validation: can material citation include multiple paragraphs in taxpub?

### ISSUE THREAD

**Issue by myrmoteras** [plazi/TaxPub#67]
@tcatapano can material citation include multiple paragraphs, or does a mc be included in a paragraph?

With other words, is this valid taxpub: https://tb.plazi.org/GgServer/taxPubL1/A56387B0FF8B7079B0C4FF1294D7F5D5

see https://docs.google.com/document/d/1tz4_Dava7-7m708tc_HmsGt3YCKBkVsx6D3_VFaE_0A/edit#  issue 16

**Comment by tcatapano** [comment]
No.  Paragraphs are not valid children of material-citaton
